name: Deploy to EC2

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies and build
        run: |
          # Install dependencies for Frontend
          cd Frontend
          npm ci
          npm run build

          # Install dependencies for Backend
          cd ../Backend
          npm ci

      - name: Deploy to EC2
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude='*/node_modules' --exclude='.git' --exclude='*/tests' --exclude='*/.env*'
          path: ./*
          remote_path: /home/ubuntu/project/
          remote_host: ${{ env.EC2_HOST }}
          remote_user: ubuntu
          remote_key: "${{ env.SSH_PRIVATE_KEY }}"

      - name: Install dependencies and restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/project
            # Install dependencies for both Frontend and Backend
            cd Frontend && npm ci --production
            cd ../Backend && npm ci --production
            # Source environment variables
            source /etc/app.env
            # Restart the systemd service
            sudo systemctl restart myapp.service
